name: workflow2
on: 
  workflow_dispatch:
  push:
   branches:
     - master
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13.x' # you can use 1.12
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - name: Upgrades flutter 
      run: flutter upgrade --force
      working-directory: ./webshop
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./webshop
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./webshop
    - name: Build Web
      run: flutter build web --base-href "/shop/"
      working-directory: ./webshop
    - name: Deploy
      run: |
        cd webshop/build/web
        git init
        git config user.name  "GeddesWorks"
        git config user.email "collin.geddes@gmail.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/GeddesWorks/shop.git
        git checkout -b gh-pages
        echo "www.geddesworks.com" > CNAME
        git add .
        git commit -m "Updated docs"
        git push --force secure-origin gh-pages
